### ISSUE TITLE
Deleting/Editing a note sometimes does not work

### ISSUE THREAD

**Issue by Garbaz** [Yanndroid/NotiNotes#6] opened 2022-07-03 04:56 UTC
- _Device:_ Fairphone 2
- _OS:_ Android 10
- _App Version:_ 1.3.2

Sometimes, when I press the "edit" or the "delete" button inside the notification, nothing happens, no matter if I re-open the detailed view of the notification, or pull the notification area back up and back down. However, if I open the dialogue to create a new note once, and exit it again, then "edit" and "delete" work again.

Unfortunately, I can't seem to find some clear steps to reproduce this reliably. Even if I "Force Stop" the app, the edit/delete buttons still work. I just create a new note, wait for a while, and then I can no longer edit or delete it. Though once that happens, I can reliably get it to work again by opening the creation dialog briefly.

**Comment by Garbaz** [comment] 2022-07-03 05:23
Looking through the code a bit, other than the possibility of the `Dialog` constructor somehow messing up, what appears as a potential origin to me might be the `if (requestPermission()) return` at the beginning of all dialogues, since `requestPermission()` appears to return false if `Settings.canDrawOverlays(context)` returns true. I.e., we don't start the dialogue if the permission already exists? Is this intended?

Of course this wouldn't explain why the normal create dialog works perfectly fine for me, and only the dialogues started from the notification itself does not.

**Comment by Yanndroid** [comment] 2022-07-03 07:12
I'm aware of this issue and the problem is that sometimes the service isn't running and therefore interactions with the notification does nothing. I've also updated the playstore description recently, mentioning this issue:

`- There is a bug which prevents the user from interacting with the notification (edit, delete, etc.). It will be fixed in the next update. In the meantime you have to add the tile in the first row (i.e. the tile has to be visible when interacting).`

I have a plan for an update that should fix this and also other stuff regarding android 12, but I'm very busy lately. I hope I can make the update by the end of next week.

**Comment by Yanndroid** [comment] 2022-07-03 07:25
What I need to do is make the BroadcastReceiver `mBroadcastReceiver` independent from the service and register it directly in manifest. But this will cause a lot of other problems, I'll also have to fix. That's why it might take some time.

**Comment by Garbaz** [comment] 2022-07-05 05:32
Alright, no hurry, I'm very happy with the app either way. Now that I have figured out a way to reliably be able to edit/delete notes, it's not much of a bother.

I'd love to contribute some code, but as evident by my gross misdiagnosis, I don't know much about Android development.

**Comment by Yanndroid** [comment] 2022-07-05 06:34
Thanks, I wouldn't blame your diagnosis though. `requestPermission()` does in fact return false if `Settings.canDrawOverlays(context)` is true. My method name is a bit misleading, because it not only requests the permission but also returns if the permission had to be requested. `if (requestPermission()) return` will then interrupt the code and not show an overlay. Another thing to mention is that this is my first app in kotlin and thus allowed me to learn the language, so the code might not be very clean and optimized.
Contribution is always welcome and I think even if you don't have a lot of experience in android development, what your doing right now is the way to go. By analyzing app source codes and trying to understand why something might not work is how you understand how the rest works imo. So keep it up and you'll be making awesome android apps soon.👌

**Comment by Yanndroid** [comment] 2022-07-19 22:47
Fixed in v1.3.3

**Closed by Yanndroid** 2022-07-19 22:47 UTC
